{% set name = "torcheval" %}
{% set version = "0.0.7" %}
{% set commit_id = "f1bc22fc67ec2c77ee519aa4af8079f4fdaa41bb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: a498dec34137bc66c9cf1adc7353a46c604dd62255884c72dcb4e2e4fc2cd7e9
    folder: pypi
  - url: https://github.com/pytorch/torcheval/archive/{{ commit_id }}.tar.gz
    sha256: 18f060f5152255635b168d1a09495d0e1c25f3418ba8fff32eeb172683c8244b
    folder: gh_archive

build:
  skip: True  # [py<38]
  number: 0
  script:
    - copy gh_archive\*requirements.txt pypi  # [win]
    - cp gh_archive/*requirements.txt pypi    # [not win]
    - cd pypi
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - pytorch >=1.11

test:
  imports:
    - torcheval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pytorch.org/torcheval/stable
  summary: |
    A library for providing a simple interface to create new metrics and an easy-to-use toolkit for metric
    computations and checkpointing.
  description: |
    A library with simple and straightforward tooling for model evaluations and a delightful user experience. At a high
    level TorchEval:
      * Contains a rich collection of high performance metric calculations out of the box. We utilize vectorization and
        GPU acceleration where possible via PyTorch.
      * Integrates seamlessly with distributed training and tools using torch.distributed
      * Is designed with extensibility in mind: you have the freedom to easily create your own metrics and leverage our toolkit.
      * Provides tools for profiling memory and compute requirements for PyTorch based models.
  license: BSD-3-Clause
  license_file: gh_archive/LICENSE
  license_family: BSD
  dev_url: https://github.com/pytorch/torcheval
  doc_url: https://pytorch.org/torcheval/stable

extra:
  recipe-maintainers:
    - boldorider4
